"use client";

import './globals.css'
import '98.css'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation';
import Window from './components/Window'
// import Home from './home/page'
// import Login from './login/page'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const AuthContext = React.createContext();
export const UserContext = React.createContext();

export default function RootLayout({ children }) {

  const [auth, setAuth] = useState(false);
  const [user, setUser] = useState({});
  const router = useRouter();

  useEffect(() => {
    const stringUser = localStorage.getItem('user')
    const currentUser = JSON.parse(stringUser)
    if (currentUser) {
      console.log(currentUser)
      setUser(currentUser);
      setAuth(true);
      router.push('/home')
    }
    else { router.push('/login') }
  }, [])


  return (
    <html lang="en">
      <body>
        <main className="main">
          <AuthContext.Provider value={{ auth, setAuth }}>
            <UserContext.Provider value={{ user, setUser }}>
              <Window children={children} mainWindow='true' title={`Welcome to A/S/L! You are logged in as ${user.username}`} ></Window>
            </UserContext.Provider>
          </AuthContext.Provider>
        </main>
        <img id='dummy-footer' src='/assets/images/dummy_footer.png' />
      </body>
    </html>
  )
}