"use client";

import './globals.css'
import '98.css'
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation';
import Window from './components/Window'
// import Home from './home/page'
// import Login from './login/page'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const AuthContext = React.createContext();

export default function RootLayout({ children }) {

  const [auth, setAuth] = useState(false);
  const [user, setUser] = useState('');
  const router = useRouter();

  useEffect(() => {
    const stringUser = localStorage.getItem('user')
    const jsonUser = JSON.parse(stringUser)
    if (jsonUser) {
      const currentUser = jsonUser.username;
      console.log(currentUser)
      setUser(currentUser);
      setAuth(true);
      // router.push('/home')
    }
    // else { router.push('/login') }
  }, [])


  return (
    <html lang="en">
      <body>
        <AuthContext.Provider value={{ auth, setAuth }}>
          <Window content={children} />
        </AuthContext.Provider>
        <img id='dummy-footer' src='/assets/images/dummy_footer.png' />
      </body>
    </html>
  )
}